import java.io.*;

/**
 * main class that have entrance in programm,create file with name foldercons and write html code in it.
 *
 * @author Gorbunov on 17.10.2016.
 */
public class FolderContents {
    /**
     * method that create file with name foldercons and write html code in it.
     *
     * @param args parameters that we can transfer to our program
     * @throws IOException exception that autogenerated when workin with file
     */
    public static void main(String[] args) throws IOException {
        try {
            HtmlDocument text = new HtmlDocument();
            String userDirectory = System.getProperty("user.dir");
            File dir = new File(userDirectory);
            File[] listOfFiles = dir.listFiles();
            for (File item : listOfFiles) {
                PassFolder passFolder = new PassFolder(item);
                text.addLine(passFolder.getType(), passFolder.getSize(), passFolder.getName(), passFolder.getDate());
            }
            FileWriter writer = new FileWriter("foldercons.html", false);
            writer.write(text.getHtml());
            writer.flush();
        }catch(Exception e) {
            System.out.println("Error");
        }
    }
}
