import java.io.*;

/**
 * main class that have entrance in programm,create file with name folderconssists and write html code in it.
 * @autohr Gorbunov on 15.10.2016.
 */
public class FolderContents {
    /**
     * method that create file with name folderconssists and write html code in it.
     * @param args parameters that we can transfer to our program
     * @throws IOException exception that autogenerated when workin with file
     */
    public static void main(String[] args) throws IOException {
        try {
            FileWriter writer = new FileWriter("foldercons.html", false);
            HtmlTable text = new HtmlTable();
            writer.write(text.getHtml());
            writer.flush();
        }catch(Exception e) {
            System.out.println("Error");
        }
    }
}
