import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.text.SimpleDateFormat;

/**
 * class that return name,date,size and type of html table
 *
 * @author Gorbunov on 17.10.2016.
 */
public class PassFolder {
    private File item;

    /**
     * constructor
     *
     * @param file about this file we gets information
     */
    public PassFolder(File file) {
        item = file;
    }

    /**
     * method that return name of file or folder
     *
     * @return name of file or folder
     */
    public String getName() {
        return item.getName();
    }

    /**
     * method that return date of creation of file or folder
     *
     * @return date of creation of file or folder
     * @throws IOException exception that autogenerated when workin with file
     */
    public String getDate() throws IOException {
        Path path = item.toPath();
        BasicFileAttributes attr = Files.readAttributes(path, BasicFileAttributes.class);
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MM.dd.yyyy");
        String creationDate = simpleDateFormat.format(attr.creationTime().toMillis());
        return creationDate;
    }

    /**
     * method that return size of file or folder
     *
     * @return size of file or folderof file or folder
     */
    public long getSize() {
        long size = 0;
        if (item.listFiles() != null) {
            for (File entry : item.listFiles()) {
                if (entry.isFile()) {
                    size += entry.length();
                }
                if (entry.isDirectory()) {
                    size += new PassFolder(entry).getSize();
                }
            }
        }
        return size;
    }

    /**
     * method that return type of file or folder
     *
     * @return type of file or folder
     */
    public String getType() {
        if (item.isDirectory()) {//check for directory(folder)
            return "DIR";
        }
        if (item.isFile()) { //check for file
            return "FILE";
        }
        return "OTHER";
    }
}
